---
- name: Install apache and php
  hosts: all
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present

    - name: Install PHP modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Create info.php file
      copy:
        become: yes
        dest: /var/www/html/info.php

        content: |
          <?php
          phpinfo();
          ?>
        notify:
          - Start Apache Service

  handlers:
    - name: Start Apache Service
      service:
        name: apache2
        enabled: yes
        state : restarted