---
- name: Install apache and php
  hosts: all
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present

    - name: Install PHP modules
      apt:
        - php
        - libapache2-mod-php
        - php-mysql
      state: present