---
- name: to install the apche server
  hosts: all
  become: yes
  tasks:
    - name: install apache
      apt:
        - name: Installing the Apache
          update_cahe: yes
          state: present