- hosts: all
  tasks:
    - package:
        name: "httpd"
        state: absent
      when:
       - ansible_os_name == "RedHat"
    - package:
        name: "apache2"
        state: absent
      when:
       - ansible_os_name == "Ubuntu"