- name: shutdown only redhat machines
  hosts: all
  tasks:
    - name: this task will shutdown the redhat/centos machines
      ansible.builtin.shell: echo "motd contains the word hi"
      when:
       - ansible_distribution_version == "20.04"