- hosts: all
  become: yes
  tasks:
    - package:
        name: "httpd"
        state: absent
      when:
       - ansible_os_family == "RedHat"
    - package:
        name: "apache2"
        state: absent
      when:
       - ansible_os_family == "Debian"